# GitLab CI Pipeline Example for Automatic VLAN Allocation
#
# This pipeline automatically allocates VLANs to new OpenShift clusters
# created via GitOps repository structure:
# sites/<site-name>/mce-tenet-clusters/mce-prod|mce-prep/<mce-cluster>/<cluster-name>.yaml
#
# Workflow:
# 1. Developer creates feature branch and adds new cluster YAML
# 2. Developer pushes branch and creates Merge Request
# 3. Pipeline runs ONLY on the MR (not on branch push)
# 4. Pipeline detects new cluster files and allocates VLANs
# 5. Pipeline commits changes back to the feature branch with [vlan-bot] tag
# 6. MR shows the updated YAML with vlanId field
# 7. Developer can review and merge the MR
#
# Features:
# - Detects new cluster creation from file changes
# - Automatically allocates VLAN from VLAN Manager API
# - Updates cluster YAML with vlanId field
# - Commits changes back to the same branch
# - Graceful degradation if VLAN Manager is unavailable
# - Respects "AutomateVlanAllocation: false" flag in cluster YAML
# - Prevents infinite loops with [vlan-bot] and [skip ci] tags
# - Only runs on Merge Requests (not on branch pushes)

stages:
  - validate
  - allocate-vlan
  - deploy

variables:
  # VLAN Manager Configuration
  VLAN_MANAGER_URL: "${VLAN_MANAGER_URL:-http://vlan-manager:8000}"
  VLAN_MANAGER_TIMEOUT: "10"  # Timeout in seconds
  VLAN_MANAGER_RETRIES: "2"   # Number of retry attempts

  # VRF Configuration (REQUIRED: Set as CI/CD variable in GitLab)
  # Examples: "Network1", "Network2", "Network3"
  # This should be configured at: Settings > CI/CD > Variables
  # VRF: "Network1"  # Must be set in GitLab CI/CD Variables

  # GitOps Repository Structure
  CLUSTERS_BASE_PATH: "sites"

# ============================================================================
# VLAN Allocation Stage
# ============================================================================
allocate-vlan:
  stage: allocate-vlan
  image: alpine:latest

  # Only run on merge request events (not on branch pushes)
  # This prevents the pipeline from running twice:
  # - Once when branch is pushed
  # - Again when MR is created
  rules:
    # Skip if commit message contains [skip ci] or [vlan-bot]
    - if: '$CI_COMMIT_MESSAGE =~ /\[skip ci\]/ || $CI_COMMIT_MESSAGE =~ /\[vlan-bot\]/'
      when: never
    # Only run on merge request pipelines
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always
    # Don't run on branch pushes to avoid duplication
    - when: never

  before_script:
    # Install required tools
    - apk add --no-cache curl jq bash git

  script:
    # Make script executable and run it
    - chmod +x scripts/allocate-vlan-ci.sh
    - ./scripts/allocate-vlan-ci.sh

  artifacts:
    reports:
      dotenv: vlan_allocation.env
    paths:
      - "sites/**/*.yaml"
    expire_in: 1 week

  # Allow failure to not block cluster creation
  allow_failure: true

# ============================================================================
# Optional: Verify VLAN Allocation Stage
# ============================================================================
verify-vlan-allocation:
  stage: validate
  image: alpine:latest

  # Only run after VLAN allocation
  needs:
    - allocate-vlan

  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: on_success
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: on_success

  before_script:
    - apk add --no-cache yq bash git

  script:
    - |
      #!/bin/bash
      echo "=================================================="
      echo "✅ Verifying VLAN Allocations"
      echo "=================================================="

      # Detect changed cluster files
      if [ "$CI_PIPELINE_SOURCE" = "merge_request_event" ]; then
        CHANGED_FILES=$(git diff --name-only origin/${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}...HEAD)
      else
        CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD)
      fi

      CLUSTER_FILES=$(echo "$CHANGED_FILES" | grep -E "sites/[^/]+/mce-tenet-clusters/(mce-prod|mce-prep)/[^/]+/[^/]+\.yaml$" || true)

      if [ -z "$CLUSTER_FILES" ]; then
        echo "[INFO] No cluster files to verify"
        exit 0
      fi

      ISSUES=0

      while IFS= read -r file; do
        if [ -z "$file" ] || [ ! -f "$file" ]; then
          continue
        fi

        echo ""
        echo "[CHECKING] $file"

        # Check if AutomateVlanAllocation is disabled
        if grep -qi "AutomateVlanAllocation:[[:space:]]*false" "$file"; then
          echo "[SKIP] Automation disabled for this cluster"
          continue
        fi

        # Check if vlanId exists
        if ! grep -qi "vlanId:[[:space:]]*[0-9]" "$file"; then
          echo "[WARNING] No vlanId found in $file"
          echo "[INFO] This cluster will be created without VLAN allocation"
          ISSUES=$((ISSUES + 1))
        else
          VLAN_ID=$(grep -i "vlanId:" "$file" | sed 's/.*vlanId:[[:space:]]*\([0-9]*\).*/\1/')
          echo "[OK] vlanId: $VLAN_ID"
        fi
      done <<< "$CLUSTER_FILES"

      echo ""
      echo "=================================================="
      echo "Verification Complete"
      echo "Potential Issues: $ISSUES"
      echo "=================================================="

      # Don't fail even if issues found - just report them
      exit 0

  allow_failure: true

# ============================================================================
# Example Deploy Stage (reference)
# ============================================================================
# deploy-cluster:
#   stage: deploy
#   script:
#     - echo "Deploying clusters with allocated VLANs..."
#     - # Your cluster deployment logic here
