# GitLab CI Pipeline Example for Automatic VLAN Allocation
#
# This pipeline automatically allocates VLANs to new OpenShift clusters
# created via GitOps repository structure:
# sites/<site-name>/mce-tenet-clusters/mce-prod|mce-prep/<mce-cluster>/<cluster-name>.yaml
#
# Workflow:
# 1. Developer creates feature branch and adds new cluster YAML
# 2. Developer pushes branch and creates Merge Request
# 3. Pipeline runs ONLY on the MR (not on branch push)
# 4. Pipeline detects new cluster files and allocates VLANs
# 5. Pipeline commits changes back to the feature branch with [vlan-bot] tag
# 6. MR shows the updated YAML with vlanId field
# 7. Developer can review and merge the MR
#
# Features:
# - Detects new cluster creation from file changes
# - Automatically allocates VLAN from VLAN Manager API
# - Updates cluster YAML with vlanId field
# - Commits changes back to the same branch
# - Graceful degradation if VLAN Manager is unavailable
# - Respects "AutomateVlanAllocation: false" flag in cluster YAML
# - Prevents infinite loops with [vlan-bot] and [skip ci] tags
# - Only runs on Merge Requests (not on branch pushes)

stages:
  - validate
  - allocate-vlan
  - deploy

variables:
  # VLAN Manager Configuration
  VLAN_MANAGER_URL: "${VLAN_MANAGER_URL:-http://vlan-manager:8000}"
  VLAN_MANAGER_TIMEOUT: "10"  # Timeout in seconds
  VLAN_MANAGER_RETRIES: "2"   # Number of retry attempts

  # VRF Configuration (REQUIRED: Set as CI/CD variable in GitLab)
  # Examples: "Network1", "Network2", "Network3"
  # This should be configured at: Settings > CI/CD > Variables
  # VRF: "Network1"  # Must be set in GitLab CI/CD Variables

  # GitOps Repository Structure
  CLUSTERS_BASE_PATH: "sites"

# ============================================================================
# VLAN Allocation Stage
# ============================================================================
allocate-vlan:
  stage: allocate-vlan
  image: alpine:latest

  # Only run on merge request events (not on branch pushes)
  # This prevents the pipeline from running twice:
  # - Once when branch is pushed
  # - Again when MR is created
  rules:
    # Skip if commit message contains [skip ci] or [vlan-bot]
    - if: '$CI_COMMIT_MESSAGE =~ /\[skip ci\]/ || $CI_COMMIT_MESSAGE =~ /\[vlan-bot\]/'
      when: never
    # Only run on merge request pipelines
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always
    # Don't run on branch pushes to avoid duplication
    - when: never

  before_script:
    # Install required tools
    - apk add --no-cache curl jq yq bash git

  script:
    - |
      #!/bin/bash
      set -e  # Exit on error, but we'll handle errors gracefully

      echo "=================================================="
      echo "ðŸŒ VLAN Manager - Automatic Allocation Pipeline"
      echo "=================================================="
      echo ""

      # Configuration
      VLAN_MANAGER_URL="${VLAN_MANAGER_URL}"
      VLAN_MANAGER_TIMEOUT="${VLAN_MANAGER_TIMEOUT}"
      VLAN_MANAGER_RETRIES="${VLAN_MANAGER_RETRIES}"

      # VRF Configuration - REQUIRED CI Variable
      if [ -z "${VRF}" ]; then
        echo -e "${RED}[ERROR]${NC} VRF variable is not set!"
        echo -e "${RED}[ERROR]${NC} Please configure VRF in GitLab CI/CD Variables"
        echo -e "${RED}[ERROR]${NC} Settings > CI/CD > Variables > Add Variable"
        echo -e "${RED}[ERROR]${NC} Example values: Network1, Network2, Network3"
        exit 1
      fi

      echo -e "${BLUE}[INFO]${NC} Using VRF: ${VRF}"

      # Colors for output
      GREEN='\033[0;32m'
      YELLOW='\033[1;33m'
      RED='\033[0;31m'
      BLUE='\033[0;34m'
      NC='\033[0m' # No Color

      # ========================================================================
      # Function: Check VLAN Manager Health
      # ========================================================================
      check_vlan_manager_health() {
        echo -e "${BLUE}[INFO]${NC} Checking VLAN Manager health at ${VLAN_MANAGER_URL}..."

        local http_code
        http_code=$(curl -s -o /dev/null -w "%{http_code}" \
          --connect-timeout "${VLAN_MANAGER_TIMEOUT}" \
          --max-time "${VLAN_MANAGER_TIMEOUT}" \
          "${VLAN_MANAGER_URL}/api/health" 2>/dev/null || echo "000")

        if [ "$http_code" = "200" ]; then
          echo -e "${GREEN}[SUCCESS]${NC} VLAN Manager is healthy (HTTP ${http_code})"
          return 0
        else
          echo -e "${YELLOW}[WARNING]${NC} VLAN Manager is not available (HTTP ${http_code})"
          return 1
        fi
      }

      # ========================================================================
      # Function: Extract Site from File Path
      # ========================================================================
      extract_site_from_path() {
        local file_path="$1"

        # Extract site name from path: sites/<site-name>/...
        if [[ "$file_path" =~ sites/([^/]+)/ ]]; then
          echo "${BASH_REMATCH[1]}"
          return 0
        else
          echo ""
          return 1
        fi
      }

      # ========================================================================
      # Function: Extract Cluster Name from File Path
      # ========================================================================
      extract_cluster_name() {
        local file_path="$1"

        # Extract filename without extension
        local filename=$(basename "$file_path")
        echo "${filename%.yaml}"
      }

      # ========================================================================
      # Function: Check if Automation is Enabled
      # ========================================================================
      check_automation_enabled() {
        local file_path="$1"

        # Check if file contains "AutomateVlanAllocation: false"
        if grep -qi "AutomateVlanAllocation:[[:space:]]*false" "$file_path"; then
          return 1  # Automation disabled
        else
          return 0  # Automation enabled (default)
        fi
      }

      # ========================================================================
      # Function: Check if VLAN Already Allocated
      # ========================================================================
      check_vlan_exists() {
        local file_path="$1"

        # Check if file already contains vlanId field
        if grep -qi "vlanId:[[:space:]]*[0-9]" "$file_path"; then
          return 0  # VLAN exists
        else
          return 1  # VLAN not found
        fi
      }

      # ========================================================================
      # Function: Allocate VLAN from Manager
      # ========================================================================
      allocate_vlan() {
        local cluster_name="$1"
        local site="$2"
        local vrf="${3:-$VRF}"

        echo -e "${BLUE}[INFO]${NC} Allocating VLAN for cluster: ${cluster_name} at site: ${site} (VRF: ${vrf})"

        local response
        local http_code
        local attempt=1

        while [ $attempt -le "$VLAN_MANAGER_RETRIES" ]; do
          echo -e "${BLUE}[INFO]${NC} Attempt ${attempt}/${VLAN_MANAGER_RETRIES}..."

          # Make API call to allocate VLAN
          response=$(curl -s -w "\n%{http_code}" \
            --connect-timeout "${VLAN_MANAGER_TIMEOUT}" \
            --max-time "${VLAN_MANAGER_TIMEOUT}" \
            -X POST "${VLAN_MANAGER_URL}/api/allocate-vlan" \
            -H "Content-Type: application/json" \
            -d "{\"cluster_name\":\"${cluster_name}\",\"site\":\"${site}\",\"vrf\":\"${vrf}\"}" \
            2>/dev/null)

          # Extract HTTP code and response body
          http_code=$(echo "$response" | tail -n1)
          response_body=$(echo "$response" | head -n-1)

          if [ "$http_code" = "200" ]; then
            # Extract VLAN ID from response
            local vlan_id
            vlan_id=$(echo "$response_body" | jq -r '.vlan_id' 2>/dev/null)

            if [ -n "$vlan_id" ] && [ "$vlan_id" != "null" ]; then
              echo -e "${GREEN}[SUCCESS]${NC} Allocated VLAN ID: ${vlan_id}"
              echo "$vlan_id"
              return 0
            else
              echo -e "${RED}[ERROR]${NC} Failed to parse VLAN ID from response"
            fi
          elif [ "$http_code" = "400" ]; then
            # Bad request - might already be allocated
            echo -e "${YELLOW}[WARNING]${NC} Allocation failed (HTTP ${http_code}): ${response_body}"
            echo ""
            return 1
          elif [ "$http_code" = "404" ]; then
            # No available VLANs
            echo -e "${RED}[ERROR]${NC} No available VLANs at site ${site} (HTTP ${http_code})"
            echo ""
            return 1
          else
            echo -e "${YELLOW}[WARNING]${NC} Allocation failed (HTTP ${http_code}), retrying..."
          fi

          attempt=$((attempt + 1))
          sleep 2
        done

        echo -e "${RED}[ERROR]${NC} Failed to allocate VLAN after ${VLAN_MANAGER_RETRIES} attempts"
        echo ""
        return 1
      }

      # ========================================================================
      # Function: Add VLAN ID to Cluster YAML
      # ========================================================================
      add_vlan_to_yaml() {
        local file_path="$1"
        local vlan_id="$2"

        echo -e "${BLUE}[INFO]${NC} Adding vlanId: ${vlan_id} to ${file_path}..."

        # Check if vlanId already exists
        if grep -qi "vlanId:" "$file_path"; then
          echo -e "${YELLOW}[WARNING]${NC} vlanId field already exists, updating..."
          # Update existing vlanId
          sed -i "s/vlanId:[[:space:]]*[0-9]*/vlanId: ${vlan_id}/I" "$file_path"
        else
          # Add vlanId field at the end of the file
          echo "vlanId: ${vlan_id}" >> "$file_path"
        fi

        echo -e "${GREEN}[SUCCESS]${NC} Updated ${file_path} with vlanId: ${vlan_id}"
      }

      # ========================================================================
      # MAIN LOGIC
      # ========================================================================

      echo -e "${BLUE}[INFO]${NC} Detecting changed cluster files..."

      # Detect changed files in the MR or commit
      # For merge requests, compare against target branch
      # For commits to main, compare against previous commit
      if [ "$CI_PIPELINE_SOURCE" = "merge_request_event" ]; then
        CHANGED_FILES=$(git diff --name-only --diff-filter=A origin/${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}...HEAD)
      else
        CHANGED_FILES=$(git diff --name-only --diff-filter=A HEAD~1 HEAD)
      fi

      # Filter for cluster YAML files in the correct path structure
      CLUSTER_FILES=$(echo "$CHANGED_FILES" | grep -E "sites/[^/]+/mce-tenet-clusters/(mce-prod|mce-prep)/[^/]+/[^/]+\.yaml$" || true)

      if [ -z "$CLUSTER_FILES" ]; then
        echo -e "${YELLOW}[INFO]${NC} No new cluster files detected. Skipping VLAN allocation."
        exit 0
      fi

      echo -e "${GREEN}[INFO]${NC} Found $(echo "$CLUSTER_FILES" | wc -l) new cluster file(s)"
      echo ""

      # Check VLAN Manager health first
      VLAN_MANAGER_AVAILABLE=false
      if check_vlan_manager_health; then
        VLAN_MANAGER_AVAILABLE=true
      else
        echo -e "${YELLOW}[WARNING]${NC} VLAN Manager is not available. Clusters will be created without VLAN allocation."
        echo -e "${YELLOW}[WARNING]${NC} You can manually allocate VLANs later using: POST ${VLAN_MANAGER_URL}/api/allocate-vlan"
        exit 0  # Exit gracefully without failing the pipeline
      fi

      # Process each cluster file
      PROCESSED=0
      ALLOCATED=0
      SKIPPED=0
      FAILED=0

      while IFS= read -r file; do
        if [ -z "$file" ]; then
          continue
        fi

        echo ""
        echo "=================================================="
        echo -e "${BLUE}[PROCESSING]${NC} ${file}"
        echo "=================================================="

        # Extract site and cluster name
        SITE=$(extract_site_from_path "$file")
        CLUSTER_NAME=$(extract_cluster_name "$file")

        if [ -z "$SITE" ]; then
          echo -e "${RED}[ERROR]${NC} Could not extract site from path: ${file}"
          FAILED=$((FAILED + 1))
          continue
        fi

        echo -e "${BLUE}[INFO]${NC} Site: ${SITE}"
        echo -e "${BLUE}[INFO]${NC} Cluster: ${CLUSTER_NAME}"

        # Check if automation is enabled
        if ! check_automation_enabled "$file"; then
          echo -e "${YELLOW}[SKIP]${NC} AutomateVlanAllocation is disabled for this cluster"
          SKIPPED=$((SKIPPED + 1))
          continue
        fi

        # Check if VLAN is already allocated
        if check_vlan_exists "$file"; then
          echo -e "${YELLOW}[SKIP]${NC} VLAN already allocated for this cluster"
          SKIPPED=$((SKIPPED + 1))
          continue
        fi

        # Check if VLAN Manager is available
        if [ "$VLAN_MANAGER_AVAILABLE" = false ]; then
          echo -e "${YELLOW}[SKIP]${NC} VLAN Manager is not available"
          SKIPPED=$((SKIPPED + 1))
          continue
        fi

        # Allocate VLAN (using CI variable VRF)
        VLAN_ID=$(allocate_vlan "$CLUSTER_NAME" "$SITE" "$VRF")

        if [ -n "$VLAN_ID" ] && [ "$VLAN_ID" != "null" ]; then
          # Add VLAN to YAML
          add_vlan_to_yaml "$file" "$VLAN_ID"
          ALLOCATED=$((ALLOCATED + 1))
        else
          echo -e "${RED}[ERROR]${NC} Failed to allocate VLAN for ${CLUSTER_NAME}"
          FAILED=$((FAILED + 1))
          # Continue processing other clusters instead of failing
        fi

        PROCESSED=$((PROCESSED + 1))
      done <<< "$CLUSTER_FILES"

      # ========================================================================
      # Summary Report
      # ========================================================================
      echo ""
      echo "=================================================="
      echo "ðŸ“Š VLAN Allocation Summary"
      echo "=================================================="
      echo -e "Total Clusters Processed:  ${PROCESSED}"
      echo -e "${GREEN}VLANs Allocated:           ${ALLOCATED}${NC}"
      echo -e "${YELLOW}Clusters Skipped:          ${SKIPPED}${NC}"
      echo -e "${RED}Allocation Failures:       ${FAILED}${NC}"
      echo "=================================================="
      echo ""

      # Commit changes if any VLANs were allocated
      if [ $ALLOCATED -gt 0 ]; then
        echo -e "${BLUE}[INFO]${NC} Committing VLAN allocation changes..."

        git config user.name "VLAN Manager Bot"
        git config user.email "vlan-manager@automation.local"

        git add .

        # Create commit message
        COMMIT_MSG="chore: Automatic VLAN allocation for ${ALLOCATED} cluster(s) [vlan-bot]"
        git commit -m "${COMMIT_MSG}"

        echo -e "${GREEN}[SUCCESS]${NC} Changes committed"
      else
        echo -e "${YELLOW}[INFO]${NC} No changes to commit"
      fi

      # Exit successfully even if some allocations failed
      # This ensures cluster creation can proceed
      echo -e "${GREEN}[COMPLETE]${NC} VLAN allocation phase completed"
      exit 0

  artifacts:
    reports:
      dotenv: vlan_allocation.env
    paths:
      - "sites/**/*.yaml"
    expire_in: 1 week

  # Allow failure to not block cluster creation
  allow_failure: true

# ============================================================================
# Optional: Verify VLAN Allocation Stage
# ============================================================================
verify-vlan-allocation:
  stage: validate
  image: alpine:latest

  # Only run after VLAN allocation
  needs:
    - allocate-vlan

  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: on_success
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: on_success

  before_script:
    - apk add --no-cache yq bash git

  script:
    - |
      #!/bin/bash
      echo "=================================================="
      echo "âœ… Verifying VLAN Allocations"
      echo "=================================================="

      # Detect changed cluster files
      if [ "$CI_PIPELINE_SOURCE" = "merge_request_event" ]; then
        CHANGED_FILES=$(git diff --name-only origin/${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}...HEAD)
      else
        CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD)
      fi

      CLUSTER_FILES=$(echo "$CHANGED_FILES" | grep -E "sites/[^/]+/mce-tenet-clusters/(mce-prod|mce-prep)/[^/]+/[^/]+\.yaml$" || true)

      if [ -z "$CLUSTER_FILES" ]; then
        echo "[INFO] No cluster files to verify"
        exit 0
      fi

      ISSUES=0

      while IFS= read -r file; do
        if [ -z "$file" ] || [ ! -f "$file" ]; then
          continue
        fi

        echo ""
        echo "[CHECKING] $file"

        # Check if AutomateVlanAllocation is disabled
        if grep -qi "AutomateVlanAllocation:[[:space:]]*false" "$file"; then
          echo "[SKIP] Automation disabled for this cluster"
          continue
        fi

        # Check if vlanId exists
        if ! grep -qi "vlanId:[[:space:]]*[0-9]" "$file"; then
          echo "[WARNING] No vlanId found in $file"
          echo "[INFO] This cluster will be created without VLAN allocation"
          ISSUES=$((ISSUES + 1))
        else
          VLAN_ID=$(grep -i "vlanId:" "$file" | sed 's/.*vlanId:[[:space:]]*\([0-9]*\).*/\1/')
          echo "[OK] vlanId: $VLAN_ID"
        fi
      done <<< "$CLUSTER_FILES"

      echo ""
      echo "=================================================="
      echo "Verification Complete"
      echo "Potential Issues: $ISSUES"
      echo "=================================================="

      # Don't fail even if issues found - just report them
      exit 0

  allow_failure: true

# ============================================================================
# Example Deploy Stage (reference)
# ============================================================================
# deploy-cluster:
#   stage: deploy
#   script:
#     - echo "Deploying clusters with allocated VLANs..."
#     - # Your cluster deployment logic here
