apiVersion: v2
name: vlan-manager
description: A FastAPI-based VLAN segment management system with site-specific IP validation and advanced filtering
type: application
version: 2.0.0
appVersion: "2.0.0"
keywords:
  - vlan
  - network
  - management
  - fastapi
home: https://github.com/your-org/vlan-manager
sources:
  - https://github.com/your-org/vlan-manager
maintainers:
  - name: VLAN Manager Team