name: Build and Push

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Generate version
      id: version
      run: |
        LATEST_TAG=$(git tag -l "v*.*.*" | sort -V | tail -n1)
        if [[ -z "$LATEST_TAG" ]]; then
          VERSION="v1.0.0"
        else
          IFS='.' read -r MAJOR MINOR PATCH <<< "${LATEST_TAG#v}"
          PATCH=$((PATCH + 1))
          VERSION="v${MAJOR}.${MINOR}.${PATCH}"
        fi
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        git tag $VERSION
        git push origin $VERSION

    - name: Log in to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/vlan-manager:${{ steps.version.outputs.version }} .
        docker build -t ${{ secrets.DOCKER_USERNAME }}/vlan-manager:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/vlan-manager:${{ steps.version.outputs.version }}
        docker push ${{ secrets.DOCKER_USERNAME }}/vlan-manager:latest